services:
  express:
    container_name: express
    environment:
      - NODE_ENV=production
      - IN_DOCKER=true
    env_file: ./.env
    build:
      context: .
    ports:
      - 3001:3001
    command: npm run start
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    container_name: mongo
    image: mongo
    env_file: ./.env
    volumes:
      - mongodb-persist-data:/data/db
      - ./stubs-server/mongo-db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok'
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  mongodb-persist-data:
