const airportsData = [
  {
    name: 'Dubai International Airport',
    iata_code: 'DXB',
    icao_code: 'OMDB',
    lat: 25.251415,
    lng: 55.360585,
    country_code: 'AE',
  },
  {
    name: 'Sheremetyevo International Airport',
    iata_code: 'SVO',
    icao_code: 'UUEE',
    lat: 55.970288,
    lng: 37.415021,
    country_code: 'RU',
  },
  {
    name: 'Domodedovo International Airport',
    iata_code: 'DME',
    icao_code: 'UUDD',
    lat: 55.412621,
    lng: 37.901898,
    country_code: 'RU',
  },
  {
    name: 'Sharjah International Airport',
    iata_code: 'SHJ',
    icao_code: 'OMSJ',
    lat: 25.326018,
    lng: 55.518213,
    country_code: 'AE',
  },
  {
    name: 'Minsk National Airport',
    iata_code: 'MSQ',
    icao_code: 'UMMS',
    lat: 53.884898,
    lng: 28.031291,
    country_code: 'BY',
  },
  {
    name: 'Kutaisi International Airport',
    iata_code: 'KUT',
    icao_code: 'UGKO',
    lat: 42.177327,
    lng: 42.482347,
    country_code: 'GE',
  },
  {
    name: 'Tbilisi International Airport',
    iata_code: 'TBS',
    icao_code: 'UGTB',
    lat: 41.669201,
    lng: 44.9547,
    country_code: 'GE',
  },
  {
    name: 'Batumi International Airport',
    iata_code: 'BUS',
    icao_code: 'UGSB',
    lat: 41.610477,
    lng: 41.599986,
    country_code: 'GE',
  },
  {
    name: 'Astana Nursultan Nazarbayev International Airport',
    iata_code: 'NQZ',
    icao_code: 'UACC',
    lat: 51.024078,
    lng: 71.465014,
    country_code: 'KZ',
  },
];

module.exports = {
  airportsData,
};
